version: 2

project_name: myhelper

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/bkohler93/myhelper/cmd.Version={{.Version}} -X github.com/bkohler93/myhelper/cmd.Commit={{.Commit}} -X github.com/bkohler93/myhelper/cmd.Date={{.Date}}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    formats:
      - tar.gz

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  github:
    owner: bkohler93
    name: myhelper
