package scanner

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestWalk(t *testing.T) {
	t.Run("returns go file in root dir", func(t *testing.T) {
		dir := t.TempDir()
		if err := os.WriteFile(filepath.Join(dir, "main.go"), []byte("package main\n"), 0644); err != nil {
			t.Fatal(err)
		}
		paths, err := Walk(dir)
		if err != nil {
			t.Fatalf("Walk() error: %v", err)
		}
		if len(paths) != 1 {
			t.Fatalf("expected 1 path, got %d: %v", len(paths), paths)
		}
		if paths[0] != "main.go" {
			t.Errorf("expected 'main.go', got %q", paths[0])
		}
	})

	t.Run("excludes .git subdirectory", func(t *testing.T) {
		dir := t.TempDir()
		gitDir := filepath.Join(dir, ".git")
		if err := os.MkdirAll(gitDir, 0755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(gitDir, "hooks.go"), []byte("package git\n"), 0644); err != nil {
			t.Fatal(err)
		}
		paths, err := Walk(dir)
		if err != nil {
			t.Fatalf("Walk() error: %v", err)
		}
		for _, p := range paths {
			if p == ".git" || strings.HasPrefix(p, ".git"+string(filepath.Separator)) {
				t.Errorf("expected no .git paths, got %q", p)
			}
		}
	})

	t.Run("excludes vendor subdirectory", func(t *testing.T) {
		dir := t.TempDir()
		vendorDir := filepath.Join(dir, "vendor")
		if err := os.MkdirAll(vendorDir, 0755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(vendorDir, "dep.go"), []byte("package dep\n"), 0644); err != nil {
			t.Fatal(err)
		}
		paths, err := Walk(dir)
		if err != nil {
			t.Fatalf("Walk() error: %v", err)
		}
		for _, p := range paths {
			if p == "vendor" || strings.HasPrefix(p, "vendor"+string(filepath.Separator)) {
				t.Errorf("expected no vendor paths, got %q", p)
			}
		}
	})

	t.Run("excludes testdata subdirectory", func(t *testing.T) {
		dir := t.TempDir()
		testdataDir := filepath.Join(dir, "testdata")
		if err := os.MkdirAll(testdataDir, 0755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(testdataDir, "fixture.go"), []byte("package testdata\n"), 0644); err != nil {
			t.Fatal(err)
		}
		paths, err := Walk(dir)
		if err != nil {
			t.Fatalf("Walk() error: %v", err)
		}
		for _, p := range paths {
			if p == "testdata" || strings.HasPrefix(p, "testdata"+string(filepath.Separator)) {
				t.Errorf("expected no testdata paths, got %q", p)
			}
		}
	})

	t.Run("excludes .myhelper subdirectory", func(t *testing.T) {
		dir := t.TempDir()
		myhelperDir := filepath.Join(dir, ".myhelper")
		if err := os.MkdirAll(myhelperDir, 0755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(myhelperDir, "gen.go"), []byte("package myhelper\n"), 0644); err != nil {
			t.Fatal(err)
		}
		paths, err := Walk(dir)
		if err != nil {
			t.Fatalf("Walk() error: %v", err)
		}
		for _, p := range paths {
			if p == ".myhelper" || strings.HasPrefix(p, ".myhelper"+string(filepath.Separator)) {
				t.Errorf("expected no .myhelper paths, got %q", p)
			}
		}
	})

	t.Run("skips generated file", func(t *testing.T) {
		dir := t.TempDir()
		content := "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage foo\n"
		if err := os.WriteFile(filepath.Join(dir, "gen.go"), []byte(content), 0644); err != nil {
			t.Fatal(err)
		}
		paths, err := Walk(dir)
		if err != nil {
			t.Fatalf("Walk() error: %v", err)
		}
		if len(paths) != 0 {
			t.Errorf("expected no paths (generated file skipped), got %v", paths)
		}
	})

	t.Run("includes non-generated go file", func(t *testing.T) {
		dir := t.TempDir()
		if err := os.WriteFile(filepath.Join(dir, "foo.go"), []byte("package foo\n"), 0644); err != nil {
			t.Fatal(err)
		}
		paths, err := Walk(dir)
		if err != nil {
			t.Fatalf("Walk() error: %v", err)
		}
		if len(paths) != 1 {
			t.Fatalf("expected 1 path, got %d: %v", len(paths), paths)
		}
		if paths[0] != "foo.go" {
			t.Errorf("expected 'foo.go', got %q", paths[0])
		}
	})

	t.Run("returns only go files", func(t *testing.T) {
		dir := t.TempDir()
		files := map[string]string{
			"main.go":    "package main\n",
			"readme.md":  "# Readme\n",
			"config.txt": "key=value\n",
			"data.json":  `{"key": "value"}`,
		}
		for name, content := range files {
			if err := os.WriteFile(filepath.Join(dir, name), []byte(content), 0644); err != nil {
				t.Fatal(err)
			}
		}
		paths, err := Walk(dir)
		if err != nil {
			t.Fatalf("Walk() error: %v", err)
		}
		if len(paths) != 1 {
			t.Fatalf("expected only 1 .go path, got %d: %v", len(paths), paths)
		}
		if paths[0] != "main.go" {
			t.Errorf("expected 'main.go', got %q", paths[0])
		}
	})
}
